# importing system libraries
import time
from random import randrange

# importing scraping library
from bs4 import BeautifulSoup
# importing selenium libraries
from selenium import webdriver


# function for custom sleeping delay
def delay():
    time.sleep(randrange(4, 6))


if __name__ == "__main__":
    # defining path of chrome web driver and initializing it
    PATH = "C:\\Program Files (x86)\\chromedriver.exe"
    driver = webdriver.Chrome(PATH)

    # paste your link here in the parameter
    driver.get(
        'https://www.google.com/search?q=english+to+italian+translation&sxsrf=AOaemvKUZsnUzXVj7a_5Fyev9qc0EfR_EQ%3A1639485403803&ei=24-4YcGUMI2Txc8P5bOBuA8&oq=english+to+italian+translation&gs_lcp=Cgdnd3Mtd2l6EAEYADIECCMQJzIGCAAQBxAeMgUIABCABDIGCAAQBxAeMgYIABAHEB4yBggAEAcQHjIGCAAQBxAeMgYIABAHEB4yBggAEAcQHjIGCAAQBxAeOgcIABBHELADOgcIABCwAxBDOgcIIxCwAhAnSgQIQRgASgQIRhgAUJEaWLZFYJZXaAJwAngBgAG9BYgB1huSAQkzLTUuMS4xLjGYAQCgAQHIAQrAAQE&sclient=gws-wiz')
    delay()

    variable = [
        'about',
        'address',
        'alreadyHaveAccount',
        'availableCities',
        'bmiCategory',
        'bmiInfo',
        'bmiNote',
        'breakfast',
        'cameraAccessDenied',
        'camera',
        'calculate',
        'calorie',
        'contactNo',
        'carbohydrates',
        'city',
        'circuit',
        'closingTime',
        'confirmPassword',
        'continueWith',
        'cities',
        'dataIsLoading',
        'dontHaveAccount',
        'diet',
        'dinner',
        'email',
        'excercisesNote',
        'evening',
        'friday',
        'food',
        'foodItems',
        'foodDetail',
        'fat',
        'foodItemIdentified',
        'fiber',
        'foodName',
        'height',
        'imageNotIdentified',
        'ingredients',
        'imageIsProcessing',
        'ingredients',
        'lessThan',
        'lunch',
        'location',
        'login',
        'mealPlanNote',
        'midMeal',
        'monday',
        'normalWeight',
        'name',
        'nutrition',
        'nurtitionValue',
        'openingTime',
        'overWeight',
        'password',
        'price',
        'protein',
        'recipe',
        'restaurantName',
        'recipe',
        'reviews',
        'rating',
        'restaurant',
        'selectLanguage',
        'sunday',
        'signup',
        'saturday',
        'sodium',
        'sugar',
        'searchFood',
        'thursday',
        'tuesday',
        'type',
        'timing',
        'type',
        'username',
        'underWeight',
        'workout',
        'wednesday',
        'website',
        'whatIsBMI',
        'weight',
        'yourBmiIs',
        'abs',
        'back',
        'barPreacherCurls',
        'barbellCurls',
        'benchDips',
        'biceps',
        'bicycleCrunches',
        'bottomUpStanding',
        'buildMuscles',
        'butterfly',
        'buttUps',
        'cardioCircuit',
        'chest',
        'chestStretch',
        'closeGripBar',
        'coreCircuit',
        'crossOver',
        'crunches',
        'deadLift',
        'declieObliqueCrunches',
        'declinePushUp',
        'dips',
        'donkeyCalfRaise',
        'dumbellBentOver',
        'hammerCurls',
        'highKnees',
        'homeBasedWorkout',
        'hyperExtension',
        'inclineBenchDumbellPress',
        'jumpingJacks',
        'laiteralRaise',
        'legRaise',
        'loseWeight',
        'lowerBody',
        'lunges',
        'lyingLegRaise',
        'lyingTricepsExtension',
        'mountainClimbers',
        'overHeadStretch',
        'plainBenchBarbellPress',
        'plank',
        'pullups',
        'pushUps',
        'sideLegRaise',
        'sidePlank',
        'shoulders',
        'skinnyLegs',
        'smithMachineCalfRaise',
        'splitJumps',
        'splitSquat',
        'squatJumps',
        'squats',
        'swissBallCrunches',
        'toeToucherCrunches',
        'triceps',
        'tricepsDips',
        'upperBody',
        'vUpRaps',
        'calculateBMI',
        'dietforUnderWeightNormalWeight',
        'breakfastTimeNormalWeight',
        'snackTimeNormalWeight',
        'lunchTimeNormalWeight',
        'eveningTimeNormalWeight',
        'dinnerTimeNormalWeight',
        'sundayBreakfastNormalWeight',
        'sundaySnackNormalWeight',
        'sundayLunchNormalWeight',
        'sundayEveningNormalWeight',
        'sundayDinnerNormalWeight',
        'mondayBreakfastNormalWeight',
        'mondaySnackNormalWeight',
        'mondayLunchNormalWeight',
        'mondayEveningNormalWeight',
        'mondayDinnerNormalWeight',
        'tuesdayBreakfastNormalWeight',
        'tuesdaySnackNormalWeight',
        'tuesdayLunchNormalWeight',
        'tuesdayEveningNormalWeight',
        'tuesdayDinnerNormalWeight',
        'wednesdayBreakfastNormalWeight',
        'wednesdaySnackNormalWeight',
        'wednesdayLunchNormalWeight',
        'wednesdayEveningNormalWeight',
        'wednesdayDinnerNormalWeight',
        'thursdayBreakfastNormalWeight',
        'thursdaySnackNormalWeight',
        'thursdayLunchNormalWeight',
        'thursdayEveningNormalWeight',
        'thursdayDinnerNormalWeight',
        'fridayBreakfastNormalWeight',
        'fridaySnackNormalWeight',
        'fridayLunchNormalWeight',
        'fridayEveningNormalWeight',
        'fridayDinnerNormalWeight',
        'saturdayBreakfastNormalWeight',
        'saturdaySnackNormalWeight',
        'saturdayLunchNormalWeight',
        'saturdayEveningNormalWeight',
        'saturdayDinnerNormalWeight',
        'dietToMaintainWeightMaintainWeight',
        'breakfastTimeMaintainWeight',
        'snackTimeMaintainWeight',
        'lunchTimeMaintainWeight',
        'eveningTimeMaintainWeight',
        'dinnerTimeMaintainWeight',
        'sundayBreakfastMaintainWeight',
        'sundaySnackMaintainWeight',
        'sundayLunchMaintainWeight',
        'sundayEveningMaintainWeight',
        'sundayDinnerMaintainWeight',
        'mondayBreakfastMaintainWeight',
        'mondaySnackMaintainWeight',
        'mondayLunchMaintainWeight',
        'mondayEveningMaintainWeight',
        'mondayDinnerMaintainWeight',
        'tuesdayBreakfastMaintainWeight',
        'tuesdaySnackMaintainWeight',
        'tuesdayLunchMaintainWeight',
        'tuesdayEveningMaintainWeight',
        'tuesdayDinnerMaintainWeight',
        'wednesdayBreakfastMaintainWeight',
        'wednesdaySnackMaintainWeight',
        'wednesdayLunchMaintainWeight',
        'wednesdayEveningMaintainWeight',
        'wednesdayDinnerMaintainWeight',
        'thursdayBreakfastMaintainWeight',
        'thursdaySnackMaintainWeight',
        'thursdayLunchMaintainWeight',
        'thursdayEveningMaintainWeight',
        'thursdayDinnerMaintainWeight',
        'fridayBreakfastMaintainWeight',
        'fridaySnackMaintainWeight',
        'fridayLunchMaintainWeight',
        'fridayEveningMaintainWeight',
        'fridayDinnerMaintainWeight',
        'saturdayBreakfastMaintainWeight',
        'saturdaySnackMaintainWeight',
        'saturdayLunchMaintainWeight',
        'saturdayEveningMaintainWeight',
        'saturdayDinnerMaintainWeight',
        'dietForOverWeightOverWeight',
        'breakfastTimeOverWeight',
        'snackTimeOverWeight',
        'lunchTimeOverWeight',
        'eveningTimeOverWeight',
        'dinnerTimeOverWeight',
        'sundayBreakfastOverWeight',
        'sundaySnackOverWeight',
        'sundayLunchOverWeight',
        'sundayEveningOverWeight',
        'sundayDinnerOverWeight',
        'mondayBreakfastOverWeight',
        'mondaySnackOverWeight',
        'mondayLunchOverWeight',
        'mondayEveningOverWeight',
        'mondayDinnerOverWeight',
        'tuesdayBreakfastOverWeight',
        'tuesdaySnackOverWeight',
        'tuesdayLunchOverWeight',
        'tuesdayEveningOverWeight',
        'tuesdayDinnerOverWeight',
        'wednesdayBreakfastOverWeight',
        'wednesdaySnackOverWeight',
        'wednesdayLunchOverWeight',
        'wednesdayEveningOverWeight',
        'wednesdayDinnerOverWeight',
        'thursdayBreakfastOverWeight',
        'thursdaySnackOverWeight',
        'thursdayLunchOverWeight',
        'thursdayEveningOverWeight',
        'thursdayDinnerOverWeight',
        'fridayBreakfastOverWeight',
        'fridaySnackOverWeight',
        'fridayLunchOverWeight',
        'fridayEveningOverWeight',
        'fridayDinnerOverWeight',
        'saturdayBreakfastOverWeight',
        'saturdaySnackOverWeight',
        'saturdayLunchOverWeight',
        'saturdayEveningOverWeight',
        'saturdayDinnerOverWeight',

        'barbellShoulderPress',
        'shrugs',
        'enterAllFields',
        'greaterThan',
        'languageUpdated',
        'cancel',
        'postReview',
        'homeBasedWorkout',
        'declieObliqueCrunches',
        'instructions',

        'bicycleCrunchesHowToDo',
        'bottomUpStandingHowToDo',
        'buttUpsHowToDo',
        'chestStretchHowToDo',
        'crossOverHowToDo',
        'crunchesHowToDo',
        'highKneesHowToDo',
        'jumpingJacksHowToDo',
        'legRaiseHowToDo',
        'lungesHowToDo',
        'lyingLegRaiseHowToDo',
        'mountainClimbersHowToDo',
        'overHeadStretchHowToDo',
        'plankHowToDo',
        'pushUpsHowToDo',
        'sideLegRaiseHowToDo',
        'sidePlankHowToDo',
        'splitSquatsHowToDo',
        'squatsHowToDo',
        'squatJumpsHowToDo',
        'toeToucherCrunchesHowToDo',

        # // ---Build Muscles
        'benchDipsHowToDo',
        'barbellCurlsHowToDo',
        'barbellShoulderPressHowToDo',
        'barPreacherCurlsHowToDo',
        'butterflyHowToDo',
        'closeGripBarHowToDo',
        'deadLiftHowToDo',
        'declieObliqueCrunchesHowToDo',
        'dumbellBentOverHowToDo',
        'hammerCurlsHowToDo',
        'hyperExtensionHowToDo',
        'inclineBenchDumbellPressHowToDo',
        'laiteralRaiseHowToDo',
        'lyingTricepsExtensionHowToDo',
        'plainBenchBarbellPressHowToDo',
        'pullupsHowToDo',
        'shrugsHowToDo',
        'smithMachineCalfRaiseHowToDo',
        'swissBallCrunchesHowToDo',
        'tricepsDipsHowToDo',

        # ---Lose Weight
        'donkeyCalfRaiseHowToDo',
        'vUpRapsHowToDo',
        'declinePushUpHowToDo',
        'suggestions'
    ]

    englishText = [
        'About',
        'Address',
        'Already Have Account',
        'We are in Following Cities',
        'BMI Categories',
        'BMI actually stands for Body Mass Index, and it’s a really important measure for anyone trying to lose weight. Calculating your BMI using our simple BMI calculator will show you where you are now, and where would be best for you.',
        'After Calculation BMI, you can go to Diet Plans section and follow diet plans to maintain your BMI',
        'Breakfast',
        'Camera access has been denied',
        'Camera',
        'Calculate',
        'Calories',
        'Contact Number',
        'Carbohydrates',
        'City',
        'Circuit',
        'Closing Time',
        'Confirm Password',
        'Continue With',
        'Cities',
        'Data is Loading',
        'Don\'t have Account?',
        'Diet Plans',
        'Dinner',
        'Email',
        'Perform Circuit 1 of all the exercises followed by Circuit 2 & Circuit 3',
        'Evening',
        'Friday',
        'Food',
        'Food Items',
        'Food Detail',
        'Fat',
        'Food item is identified',
        'Fiber',
        'Food Nane',
        'Height',
        'Image not identified or object not found',
        'Ingredients',
        'Image is Processing...',
        'Ingredients',
        'Less than',
        'Lunch',
        'Location',
        'Login',
        'Calculate Your BMI first to follow diet plans according to your BMI',
        'Mid Day Meal',
        'Monday',
        'Normal Weight',
        'Name',
        'Nutrition Name',
        'Nutrition Value',
        'Opening Time',
        'over Weight',
        'Password',
        'Price',
        'Protein',
        'Recipe',
        'Restaurant Name',
        'Recipe',
        'Reviews',
        'Rating',
        'Restaurant',
        'Select Language',
        'Sunday',
        'Signup',
        'Saturday',
        'Sodium',
        'Sugar',
        'Search Food',
        'Thursday',
        'Tuesday',
        'Types',
        'Timing',
        'Types',
        'User Name',
        'UnderWeight',
        'Workout',
        'Wednesday',
        'Website',
        'What is BMI?',
        'Weight',
        'Your Bmi is',
        'ABS',
        'Back',
        'Bar Preacher Curls',
        'Barbell Curls',
        'Bench Dips',
        'Biceps',
        'Bicycle Crunches',
        'Bottom Up Standing',
        'build Muscles',
        'Butterfly',
        'Butt Ups',
        'Cardio Circuit',
        'Chest',
        'Chest Stretch',
        'Close Grip EZ Bar Bench Press',
        'Core Circuit',
        'Cross Over',
        'Crunches',
        'DeadLift',
        'Declie Oblique Crunches',
        'Decline Push Up',
        'Dips',
        'Donkey Calf Raise',
        'Dumbell Bent Over',
        'Hammer Curls',
        'High Knees',
        'Home Based Workout',
        'Hyper Extension',
        'Incline Bench Dumbell Press',
        'Jumping Jacks',
        'Lateral Raise',
        'Leg Raise',
        'LoseWeight',
        'Lower Body',
        'Lunges',
        'Lying Leg Raise',
        'Lying Triceps Extension',
        'Mountain Climbers',
        'OverHead Stretch',
        'Plain Bench Barbell Press',
        'Plank',
        'Pullups',
        'Push Ups',
        'Side Leg Raise',
        'Side Plank',
        'Shoulders',
        'Skinny Legs',
        'Smith Machine Calf Raise',
        'Split Jumps',
        'Split Squats',
        'Squat Jumps',
        'Squats',
        'Swiss Ball Crunches',
        'Toe Toucher Crunches',
        'Triceps',
        'Tricep Dips',
        'Upper Body',
        'V-Up Raps',
        'Calculate BMI',
        'Diet for Under Weight',
        ' (8:00-8:30AM)',
        '(11:00-11:30AM)',
        '(2:00-2:30PM)',
        '(4:00-4:30PM)',
        '(8:00-8:30PM)',
        '2 egg brown bread sandwich + green chutney + 1 cup milk + 3 cashews + 4 almonds + 2 walnuts',
        '1 cup banana shake',
        '1 cup arhar dal + 1 cup potato curry + 3 chapatti + 1/2 cup rice + 1/2 cup low fat curd + salad',
        '1 cup strawberry smoothie + 1 cup vegetable poha',
        '1.5 cup chicken curry + 3 chapatti + salad',
        '3 onion stuffed parantha + 1 cup curd + 3 cashews + 4 almonds + 2 walnuts',
        '1 cup mango shake',
        '1 cup moong dal/ chicken curry + 1 cup potato and caulifllower vegetable + 3 chapatti + 1/2 cup rice + salad',
        '1 cup pomegranate juice + 2 butter toasted bread',
        '1 cup beans potato vegetable + 3 chapatti + salad',
        '3 paneer stuffed besan cheela + green chutney + 1 cup curd + 3 cashews + 4 almonds + 2 walnuts',
        '1 apple smoothie with maple syrup',
        '1 cup masoor dal + 1 cup calocasia + 3 chapatti + 1/2 cup rice + 1 cup low curd + salad',
        '1 cup tomato soup with bread crumbs + 1 cup aloo chaat',
        '1 cup carrot peas vegetable +3 chapatti + salad',
        '1.5 cup vegetable bread upma + 1 cup milk + 3 cashews + 4 almonds + 2 walnuts',
        '1 cup ripe banana with 2 tsp ghee',
        '1 cup rajma curry + 1 cup spinach potato + 3 chapatti + 1/2 cup rice + salad',
        '1 cup vegetable juice + 1 cup upma',
        '1.5 cup parwal vegetable + 3 chapatti + salad',
        '2 cucmber potato sandwich + 1 tsp green chutney + 1 orange juice + 3 cshews + 2 walnuts + 4 almonds',
        '1 cup buttermilk + 1 cup sweet potato chaat',
        '1 cup white chana/ fish curry + 3 chapatti + 1/2 cup rice + salad',
        '1 cup almond milk + banana',
        '1 cup cauliflower potato vegetable + 3 chapatti + salad',
        '2 cup vegetable poha + 1 cup curd + 3 cashews + 4 almonds + 2 walnuts',
        '2 cups watermelon juice',
        '1 cup chana dal + 1 cup bhindi vegetable + 3 chapatti + 1/2 cup rice + salad',
        '1 cup sprouts salad + 2 potato cheela + green chutney',
        '1 cup peas mushroom vegetable + 3 chapatti + salad',
        '3 vegetable suji cheela + 1 cup strawberry shake + 4 cashews + 4 almonds + 3 walnuts',
        '	1 cup coconut water + 1 cup pomegrate',
        '1 cup mix dal + 1 cup soybean curry + 3 chapatti + 1/2 cup curd + salad',
        '1 cup fruit salad + 4 pc vegetable cutlets + green chutney',
        '1 cup karela vegetable + 3 chaptti + salad',
        'Diet To Maintain Weight',
        ' (8:00-8:30AM)',
        '(11:00-11:30AM)',
        '(2:00-2:30PM)',
        '(4:00-4:30PM)',
        '(8:00-8:30PM)',
        '1 grapefruit + 2 poached eggs + 2 slices whole-grain toast + 1 cup low-fat milk',
        '1 banana + 1 cup plain yogurt with 2 tablespoons honey + Glass of water',
        'Chicken breast (6-ounce portion) + Large garden salad + Glass of water',
        '1 cup carrot slices + 3 tablespoons hummus + 1/2 piece of pita bread + Glass of water or herbal tea',
        '1 cup steamed broccoli + 1 cup of brown rice + Sparkling water with lemon',
        '1 whole-wheat English muffin with 2 tablespoons peanut butter + 1 orange + Large glass (12 ounces) non-fat milk + 1 cup of black coffee or herbal tea',
        '2 oatmeal cookies with raisins + Glass of water, hot tea, or black coffee',
        'A turkey sandwich + 1 cup low-sodium vegetable soup + Glass of water',
        '1 cup (about 30) grapes + Glass of water or herbal tea',
        '5-ounce sirloin steak + 1 cup mashed potatoes + 1 cup cooked spinach + 1 cup green beans + Sparkling water with lemon',
        '1 medium bran muffin + 1 serving turkey breakfast sausage + 1 orange + 1 cup non-fat milk + 1 cup black coffee or herbal tea',
        '1 fresh pear + 1 cup of flavored soy milk + Glass of water, hot tea, or black coffee',
        'Low sodium chicken noodle soup with six saltine crackers + 1 medium apple + Water',
        '1 apple + 1 slice Swiss cheese + Sparkling water with lemon',
        '8-ounce serving of turkey breast meat + 1 cup baked beans + 1 cup cooked carrots + 1 cup cooked kale + 1 glass of wine',
        '1 cup whole wheat flakes + 1 banana + 1 slice whole-grain toast + 1 cup of black coffee or herbal tea',
        '1 cup grapes and 1 tangerine + Glass of water, hot tea, or black coffee',
        'Tuna wrap with 1 wheat flour tortilla + 1 sliced avocado + 1 cup non-fat milk',
        '1 cup cottage cheese (1-percent fat) + 1 fresh pineapple slice + Four graham crackers + Sparkling water with lemon',
        '1 serving lasagna + Small garden salad + 1 cup non-fat milk',
        '1 piece of French toast + 1 scrambled or poached egg + 1 serving turkey bacon + 1 cup orange juice + 1 cup black coffee or herbal tea',
        '1 cup sliced carrots + 1 cup cauliflower pieces + 2 tablespoons ranch dressing + Glass of water, hot tea, or black coffee',
        'Veggie burger on a whole grain bun + 1 cup northern (or other dry) beans + 1 cup non-fat milk',
        '1 apple + 1 pita with 2 tablespoons hummus + Sparkling water with lemon',
        '1 trout filet + 1 cup green beans + 1 cup brown rice + 1 small garden salad + 1 glass of beer + Sparkling water with lemon',
        '1 cup corn flakes + 1 banana + 1 hard-boiled egg + 1 cup black coffee or herbal tea',
        '1 cup plain yogurt with 1 tablespoon honey, 1/2 cup blueberries, and 1 tablespoon almonds + Glass of water, hot tea, or black coffee',
        '1 cup whole wheat pasta + Medium garden salad + Glass of water ',
        '1 and 1/2 cup cottage cheese + 1 fresh peach + Glass of water',
        '4 and 1/2 ounce serving of pork loin + Small garden salad + 1 small baked sweet potato + 1 cup asparagus + Sparkling water with lemon',
        '1 cup cooked oatmeal with 1/2 cup blueberries, 1/2 cup non-fat milk, and 1 tablespoon almond slivers + 2 slices turkey bacon + 1 cup non-fat milk to drink + 1 cup black coffee or herbal tea',
        '1 cup plain yogurt with 1 tablespoon honey, 1/2 cup strawberries, and 2 tablespoons almond slivers + Glass of water, hot tea, or black coffee',
        '6-ounce baked chicken breast + Large garden salad with tomatoes and onions and 2 tablespoons salad dressing + 1 baked sweet potato + 1 whole-wheat dinner roll + Glass of water ',
        '1 cup raw broccoli florets + 1 cup raw sliced carrot + 2 tablespoons veggie dip or salad dressing + 1 fresh peach + Glass of water',
        '3-ounce serving of baked or grilled salmon + 1/2 cup black beans + 1 cup Swiss chard + 1 cup brown rice + 1 whole wheat dinner roll with a pat of butter + Sparkling water with lemon',
        'Diet For Over Weight',
        ' (8:00-8:30AM)',
        '(11:00-11:30AM)',
        '(2:00-2:30PM)',
        '(4:00-4:30PM)',
        '(8:00-8:30PM)',
        '3 egg whites + 1 toasted brown bread + 1/2 cup low fat milk (no sugar)',
        '1 cup papaya',
        '1 cup arhar dal + 1 chapatti + 1/2 cup low fat curd + salad',
        '1 cup vegetable soup',
        '1 cup pumpkin + 1 chapatti + salad',
        '1 onion stuffed chapatti + 1/2 cup low fat curd',
        '1 cup coconut water',
        '1 cup moong dal/ chicken curry + 1 chapatti + salad',
        '1 cup pomegranate',
        '1 cup beans + 1 chapatti + salad',
        '2 besan cheela + 1/2 cup low fat curd',
        '1 apple',
        '1 cup masoor dal + 1 chapatti + 1/2 up low fat curd + salad',
        '1 cup tomato soup',
        '1 cup carrot peas vegetable +1 chapatti + salad',
        '1 cup vegetable brown bread upma + 1/2 cup low fat milk (no sugar)',
        '1 cup musk melon',
        '1 cup rajma curry + 1 chapatti + salad',
        '1 cup vegetable soup',
        '1 cup parwal vegetable + 1 chapatti + salad',
        '1 cucmber hungcurd sandwich + 1/2 tsp green chutney + 1 orange',
        '1 cup buttermilk',
        '1 cup white chana/ fish curry + 1 chapatti + salad',
        '1 cup low fat milk (no sugar)',
        '1 cup cauliflower vegetable + 1 chapatti + salad',
        '1 cup vegetable poha + 1 cup low fat curd',
        '1 cup watermelon',
        '1 cup chana dal + 1 chapatti + salad',
        '1 cup sprouts salad',
        '1 cup tinda vegetable + 1 chapatti + salad',
        '1 cup low fat milk with oats + 3-4 strawberries',
        '1 cup coconut water',
        '1 cup soybean curry + 1 chapatti + 1/2 cup low fat curd + salad',
        '1 cup fruit salad',
        '1 cup ghia vegetable + 1 chaptti + salad',

        'Barbell Shoulder Press',
        'Shrugs',
        'Please fill all fields',
        'Greater Than',
        'Language has been updated',
        'cancel',
        'Post Review',
        'Home Based Workout ( Weekly )',
        'Decline Oblique Crunches',
        'Instructions',

        'Bicycle Crunch is basically for the lower abs. But along with abs, this performs as a leg exercise also. *1. Lie on your back on the floor or on a mat with knees bent, feet on the floor and hands behind your head. *2. Press your lower back into the mat and tighten your ab muscles as you lift your head, shoulders and upper back off the floor and simultaneously move your right elbow and left knee toward each other while straightening your right leg without touching it on the ground. *Reference: *Start doing as the man in the image is doing.',
        '*1. Begin by lying on your back on the ground. Your legs should be straight and your arms at your side. This will be your starting position. *2. To perform the movement, tuck the knees toward your chest by flexing the hips and knees. Extend your legs directly above you so that they are perpendicular to the ground. Rotate and elevate your pelvis to raise your glutes from the floor. *3. After a brief pause, return to the starting position. *Reference: Start doing as the man in the image is doing.',
        '*1. Begin a pushup position but with your elbows on the ground and resting on your forearms. *2. Arch your back slightly out rather than keeping your back completely straight. *3. Raise your glutes toward the ceiling, squeezing your abs tightly to close the distance between your ribcage and hips. The end result will be that you\'ll end up in a high bridge position. Exhale as you perform this portion of the movement. *4. Lower back down slowly to your starting position as you breathe in. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand with your hands together, arms extended directly in front of you. This will be your starting position. *2. Keeping your arms straight, quickly move your arms back as far as possible and back in again, similar to a clapping motion. Repeat for the recommended number of repetitions, increasing speed as you do so. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand with your feet shoulder width apart. This will be your starting position. *2. Perform a rear lunge by stepping back with one foot and flexing the hips and front knee. As you do so, rotate your torso across the front leg. *3. After a brief pause, return to the starting position and repeat on the other side, continuing in an alternating fashion. *Reference: Start doing as the man in the image is doing.',
        'The crunches is one of the most common abdominal exercises. *1. Lie on your back on a mat with knees bent, feet on the floor and hands behind your head. Now raise your head and shoulders towards your stomach. Don\'t raise the lower back, it should be stable with the floor. *Reference: Start doing as the man in the image is doing.',
        "*1. Begin standing with your feet shoulder-width apart. Your arms should be bent. *2. Lift your right knee up until it reaches your waist. Your left arm should swing forward while your right arm swings back. *3. Return your right foot to the ground as you lift your left knee. Swing your right arm forward and your left arm back. *4. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.",
        '*1. Stand with your feet together. In one motion, jump your feet out to the side and raise your arms above your head. *2. Reverse the motion by jumping back to the starting positionon. *3. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand next to a chair or other support, holding on with one hand. *2. Swing your leg forward, keeping the leg straight. Continue with a downward swing, bringing the leg as far back as your flexibility allows. *3. Repeat for the recommended number of repetitions and then switch legs. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand with your torso upright. This will be your starting position. *2. Step forward with your right leg and lower your upper body down, while keeping the torso upright and maintaining balance. *Note: Do not allow your front foot knee to go forward beyond your toes as you come down. *3. Using the heel of your foot, push up and go back to the starting position as you exhale. *4. Repeat the movement for recommended number of repetitions and then perform with the left leg. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie with your back flat on a bench and your legs extended in front of you off the end. *2. Place your hands either under your glutes with your palms down or by the sides holding on to the bench. This will be your starting position. *3. As you keep your legs extended, straight as possible with your knees slightly bent but locked raise your legs until they make a 90-degree angle with the floor. Exhale as you perform this portion of the movement and hold the contraction at the top for a second. Now, as you inhale, slowly lower your legs back down to the starting position. *Reference: Start doing as the man in the image is doing.',
        '*1. Begin in a position, with your body supported by your hands and toes. *2. Flexing the knee and hip, bring one leg until the knee is approximately under the hip. This will be your starting position. *3. Jump and reverse the positions of your legs, extending the bent leg until the leg is straight and supported by the toe, and bringing the other foot up with the hip and knee flexed. *4. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Standing straight up, lace your fingers together and open your palms to the ceiling. Keep your shoulders down as you extend your arms up. *2. To create a full torso stretch, pull your tailbone down and stabilize your torso as you do this. Stretch the muscles on both the front and the back of the torso. *Reference: Start doing as the man in the image is doing.',
        '*1. Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder. *2.Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised. *Reference: Start doing as the man in the image is doing.',
        '*1. Your arms should be fully extended with the hands around shoulder width. Keep your body straight throughout the movement. This will be your starting position. *2. Descend by flexing at the elbow, lowering your chest toward the ground. *3. At the bottom, reverse the motion by pushing yourself up through elbow extension as quickly as possible until you are air borne. *4. Return to the starting position and repeat the exercise, working all the way around until you are back where you started. 6. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand next to a chair, which you may hold onto as a support. Stand on one leg. This will be your starting position. *2. Keep your leg straight, raise it as far out to the side as possible, and swing it back down, allowing it to cross the opposite leg. *3. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie on your side and support your body between your forearm and knee to your feet. *2. Repeat on the other side. *3. Build up to at least 60 seconds on each side of your body. *Reference: Start doing as the man in the image is doing.',
        '*1. Facing away from the setup, place your rear foot into the handle behind you. Keep your head looking forward and your chest up, with your knee slightly bent. This will be your starting position *2. Descend by flexing the knee and hips, lowering yourself to the ground. *3. At the bottom of the movement, reverse the motion, extending through the hip and knee to return to the starting position. *4. Perform with the Right Foot also. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand with your feet shoulder width apart. You can place your hands behind your head. This will be your starting position. *2. Begin the movement by flexing your knees and hips, sitting back with your hips. *3. Continue down to full depth if you are able, and quickly reverse the motion until you return to the starting position. As you squat, keep your head and chest up and push your knees out. *Reference: Start doing as the man in the image is doing.',
        '*1. With your head up and your back straight, position your feet at shoulder width. *2. Keeping your back straight and chest up, squat down as you inhale. *3. Now pressing mainly with the toes of your feet, jump straight up in the air as high as possible, using the thighs like springs. Exhale during this portion of the movement. *4. When you touch the floor again, immediately squat down and jump again. *5. Repeat for the recommended number of repetitions. *Precaution: Do not perform this movement if you have any knee or back injuries due to the impact involved. *Reference: Start doing as the man in the image is doing.',
        '*1. Start by lying down on the floor or an exercise mat with your back pressed against the floor. Your arms should be lying across your sides with the palms facing down. *2. Your legs should be touching each other. Slowly raise your legs up in the air until they are almost perpendicular to the floor with a slight bend at the knees. Your feet should be parallel to the floor. *3. Move your arms so that they are fully extended at a 45 degree angle from the floor. This is the starting position. *4. While keeping your lower back pressed against the floor, slowly lift your torso and use your hands to try and touch your toes. *Remember to exhale while perform this part of the exercise. *5.Slowly begin to lower your torso and arms back down to the starting position while inhaling. *Remember to keep your arms straight out pointing towards your toes 6. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',

        # // ---Build Muscles
        'For this exercise you will need to place a bench behind your back and another one in front of you. With the benches perpendicular to your body, hold on to one bench on its edge with the hands close to your body, separated at shoulder width. Your arms should be fully extended. *1. The legs will be extended forward on top of the other bench. Your legs should be parallel to the floor while your torso is to be perpendicular to the floor. This will be your starting position. *2. Slowly lower your body as you inhale by bending at the elbows. *Note: Keep the elbows as close as possible throughout the movement. *3. Forearms should always be pointing down. *4. Using your triceps to bring your torso up again, lift yourself back to the starting position while exhaling. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position. *2. While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. *Note: Only the forearms should move. *3. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard. *4. Slowly begin to bring the bar back to starting position as your breathe in. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Sit on a bench with back support in a squat rack. Position a barbell at a height that is just above your head. Grab the barbell with a pronated grip (palms facing forward). *2. Once you pick up the barbell with the correct grip width, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position. *3. Lower the bar down to the shoulders slowly as you inhale. *4. Lift the bar back up to the starting position as you exhale. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle. *2. The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar. *3. With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position. *4. As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched. *5. As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second. 6. Repeat for the recommended number of repetitions.',
        '*1. Sit on the machine with your back flat on the pad. *2. Take hold of the handles. *Note: Your upper arms should be positioned parallel to the floor.Adjust the machine accordingly. This will be your starting position. *3.Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this motion and hold the contraction for a for sometime. *4. Return back to the starting position slowly and breathe in until your chest muscles are fully stretched. *5. Repeat these motions for the recommended amount of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie on a flat bench with an EZ bar loaded to an appropriate weight. *2. Using a narrow grip lift the bar and hold it straight over your torso with your elbows in. The arms should be perpendicular to the floor. This will be your starting position. *3. Now lower the bar down to your lower chest as you breathe in. Keep the elbows in as you perform this movement. *4. Using the triceps to push the bar back up, press it back to the starting position by extending the elbows as you exhale. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an over/under grip. *2. With your feet and your grip set, take a big breath and then lower your hips and flex the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward. *3. After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar. *4. Lower the bar by bending at the hips and guiding it to the floor. *5. Repeat the exercise for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Secure your legs at the end of the decline bench and slowly lay down on the bench. *2. Put one hand beside your head and the other on your thigh. This will be your starting position. *3. Raise your upper body slowly from the starting position while turning your torso to the left. Continue crunching up as you exhale until your right elbow touches your left knee. Hold this contracted position for a second. Tip: Focus on keeping your abs tight and keeping the movement slow and controlled. *4. Lower your body back down slowly to the starting position as you inhale. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. With a dumbbell in each hand with palms facing your torso, bend your knees slightly and bring your torso forward by bending at the waist, as you bend make sure to keep your back straigh until it is almost parallel to the floor. *Note: Make sure that you keep the head up. *2. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position. *3. While keeping the torso stationary, lift the dumbbells to your side as you breathe out, keeping the elbows close to the body. On the top contracted position, squeeze the back muscles and hold for a second. *4. Slowly lower the weight again to the starting position as you inhale. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand up with a dumbbell in each hand being held at arms length. The elbows should be close to the torso. *2. The palms of the hands should be facing your torso. This will be your starting position. *3. While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. *Note: Only the forearms should move. *4. Slowly begin to bring the dumbbells back to starting position as your breathe in. *5. Repeat the movement with the left hand. This equals one repetition. 6. Continue alternating in this manner for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie face down on a hyperextension bench, tucking your ankles securely under the footpads. *2. Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction. *3. With your body straight, cross your arms in front of you (my p*reference) or behind your head. This will be your starting position. *Note: You can also hold a weight plate for extra resistance in front of you under your crossed arms. *4. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. *Note: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back. *5. Slowly raise your torso back to the initial position as you inhale. *Note: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury. 6. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie back on an incline bench with a dumbbell in each hand. The palms of your hands will be facing each other. *2. Lift the dumbbells one at a time so that you can hold them at shoulder width. *3. Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position. *4. Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest. *5. Lock your arms at the top, hold for a second, and then start slowly lowering the weight. *Note: Llowering the weights should take about twice time as raising them. 6. Repeat the movement for the recommended number of repetitions. *Precaution: When you are done with the exercise, do not drop the dumbbells next to you as this is dangerous to your shoulders and others people working around you. Always try to hand over the dumbbell to a spotter when you are done. If using really heavy weights, it is best if a partner gives them to you as you lay down. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand up with a dumbbell in each hand being held at arms length. The elbows should be close to the torso. *2. The palms of the hands should be facing your torso. Your feet should be about shoulder width apart. This will be your starting position. *3. Keeping your arms straight and the torso stationary, lift the weights out to your sides until they are about shoulder level height while exhaling. *4. Feel the contraction for a second and begin to lower the weights back down to the starting position while inhaling. *Note: Keep the palms facing down with the little finger slightly higher while lifting and lowering the weights as it will concentrate the stress on your shoulders mainly. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. While holding a barbell with a grip with palms facing forward, lie on your back on a flat bench with your head close to the end of the bench. *2. Extend your arms in front of you and slowly bring the bar back in a semi circular motion (while keeping the arms extended) to a position over your head. At the end of this step your arms should be overhead and parallel to the floor. This will be your starting position. *Note: Keep your elbows in at all times. *3. As you inhale, lower the bar by bending at the elbows and while keeping the upper arm stationary. Keep lowering the bar until your forearms are perpendicular to the floor. *4. As you exhale bring the bar back up to the starting position by pushing the bar up in a semi-circular motion until the lower arms are also parallel to the floor. Contract the triceps hard at the top of the movement for a second. *Note: Only the forearms should move. The upper arms should remain stationary at all times. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie back on a flat bench. Using a medium width grip , lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position. *2. From the starting position, breathe in and start coming down slowly until the bar touches your middle chest. *3. After a brief pause, push the bar back to the starting position as you breathe out. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. *Note: Lowering the weight should take about twice time than raising it. *4. Repeat the movement for the recommended of repetitions. *Precaution: If you are new at this exercise, it is advised that you use a spotter. *Reference: Start doing as the man in the image is doing.',
        '*1. Grab the pull-up bar with the palms facing forward using the prescribed grip *Note: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width. *2. As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around *30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position. *3. Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. *Note: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar. *4. After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched. *5. Repeat this motion for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated grip (palms facing the thighs). This will be your starting position. *Note: Your hands should be a little wider than shoulder width apart. *2. Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. *3. Slowly return to the starting position as you breathe in. *4. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Place a block or weight plate below the bar on the Smith machine. *2. Set the bar to a position that best matches your height. Once the correct height is chosen and the bar is loaded, step onto the plates with the balls of your feet and place the bar on the back of your shoulders. *3. Take the bar with both hands facing forward. Rotate the bar to unrack it. This will be your starting position. *4. Raise your heels as high as possible by pushing off of the balls of your feet, flexing your calf at the top of the contraction. Your knees should remain extended. Hold the contracted position for a second before you start to go back down. *5. Return slowly to the starting position as you breathe in while lowering your heels. 6. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie on an exercise ball with your lower back pressed against the surface of the ball. Your feet should be bent at the knee. *2. The upper torso should be hanging off the top of the ball. This will be your starting position. *3. With the hips stationary, flex the waist by contracting the abdominals and curl the shoulders and trunk upward until you feel a nice contraction on your abdominals. Exhale as you perform this movement and hold the contraction for a second. *4. As you inhale, go back to the starting position. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. To get into the starting position, hold your body at arm\'s length with your arms nearly locked above the bars. *2. Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. *3. Then, exhale and push your torso back up using your triceps to bring your body back to the starting position. *4. Repeat the movement for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',

        # //---Lose Weight
        'For this exercise you will need access to a donkey calf raise machine. *1. Start by positioning your lower back and hips under the padded lever provided. The tailbone area should be the one making contact with the pad. *2. Place both of your arms on the side handles and place the balls of your feet on the calf block with the heels extending off. Align the toes forward, inward or outward, depending on the area you wish to target, and straighten the knees without locking them. This will be your starting position. *3. Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. *4. Hold the contracted position by a second before you start to go back down. *5. Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched. 6. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie flat on the floor or exercise mat on your back with your arms extended straight back behind your head and your legs extended also. This will be your starting position. *2. As you exhale, bend at the waist while simultaneously raising your legs and arms to meet in a jackknife position. *Note: The legs should be extended and lifted at approximately a 35-45 degree angle from the floor and the arms should be extended and parallel to your legs. The upper torso should be off the floor. *3. While inhaling, lower your arms and legs back to the starting position. *4. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        '*1. Lie on the floor face down and and on your palms. *2. Place your toes on top of a flat bench. This will allow your body to be elevated. *Note: The higher the elevation, the higher the resistance of the exercise is. *3. Lower yourself until your chest almost touches the floor. *4. Come back to the starting position. *5. Repeat for the recommended number of repetitions. *Reference: Start doing as the man in the image is doing.',
        'Suggestions'
    ]

    textFile = open('TranslationFileItalian.txt', 'a')
    for i in range(51, len(variable)):
        textArea = driver.find_element_by_id('tw-source-text-ta')
        textArea.click()
        textArea.send_keys(englishText[i])
        delay()
        htmlText = driver.page_source
        soup = BeautifulSoup(htmlText, 'lxml')
        convertedText0 = soup.find('pre', id='tw-target-text')
        convertedText = convertedText0.find('span').text

        string = variable[i] + ': \'' + convertedText + '\',\n'
        textFile.write(string)
        print(i + 1)
        button = driver.find_element_by_id('tw-cst')
        cross = button.find_element_by_class_name('tw-menu-btn-image')
        cross.click()
    textFile.close()
